server:
  port: 8002
spring:
  profiles:
    active: dev
  application:
    name: order
  datasource:
    dynamic:
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 10000
        time-between-eviction-runs-millis: 10000
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/seata_demo?characterEncoding=utf8&useSSL=false
          username: root
          password: liwenjie
        slave:
          url: jdbc:mysql://localhost:3306/seata_demo?characterEncoding=utf8&useSSL=false
          username: root
          password: liwenjie
    druid:
      use-ping-method: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      # 读超时
      timeout: 3000
      # 连接超时
      connectTimeout: 5000
      # Lettuce连接池
      lettuce:
        pool:
          # 最小空闲连接
          min-idle: 5
          # 最大空闲连接
          max-idle: 10
          # 最大连接数
          max-active: 100
          # 连接分配应该阻塞的最大时间
          max-wait: 2000
    mongodb:
      uri: mongodb://127.0.0.1:27017/test
  cloud:
    nacos:
      server-addr: localhost:8848

mybatis-plus:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true
logging:
  level:
    root: WARN
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-tc-server
#      username: nacos
#      password: nacos
      secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
      cluster: SH
  tx-service-group: seata-demo # 事务组名称
  data-source-proxy-mode: AT
#  service:
#    vgroup-mapping: # 事务组与cluster的映射关系
#      seata-demo: SH
  application-id: order
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      data-id: client.properties




obvcloud:
  datasource:
    is-master-slave: true
    is-tenant: false
  sms:
    aliyun:
      accessKeyId: LTAI5t75bc7rrQxcqY5FbxYw
      accessKeySecret: g84y30WHIJupWzZj10INly9SaROMfR
      endpoint: dysmsapi.aliyuncs.com
    baidu:
      access-key-id: ALTAKqkRcWh05Y7OpLUXiJWqnE
      access-key-secret: a72e79a163674757966eeb26355eb8b3
      endpoint: http://smsv3.bj.baidubce.com
  upload:
    local-root-path: /Users/liwenjie/www
  feishu:
    bot-key: acfb64a7-eb8e-4987-8b38-3082fba988f2


